#=====================================================
# VERBOSITY
#=====================================================

/control/execute mac/verbose.mac

#=====================================================
# VISUALISATION
#=====================================================

#/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase   data/LinacMaterials.db

# -----------------------------------------------------
# WORLD
# -----------------------------------------------------

/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    1 m
/gate/world/geometry/setYLength    1 m
/gate/world/geometry/setZLength    3 m
/gate/world/vis/setColor           black

# -----------------------------------------------------
# LINAC HEAD
# -----------------------------------------------------

/control/execute                     mac/linac_head.mac

# -----------------------------------------------------
# VIRTUAL PLANE FOR PHASE SPACE
# -----------------------------------------------------

/gate/linac/daughters/name                PhS_Source
/gate/linac/daughters/insert              cylinder
/gate/PhS_Source/setMaterial              Vacuum
/gate/PhS_Source/geometry/setRmin         0 cm
/gate/PhS_Source/geometry/setRmax         10 cm
/gate/PhS_Source/geometry/setHeight       1 nm
/gate/PhS_Source/placement/setTranslation 0.0 0.0 -22 cm

# -----------------------------------------------------
# WATER BOX
# -----------------------------------------------------
/gate/world/daughters/name              waterbox
/gate/world/daughters/insert            box
/gate/waterbox/setMaterial              Water
/gate/waterbox/placement/setTranslation 0 0 -124.25 cm 
/gate/waterbox/geometry/setXLength      485 mm
/gate/waterbox/geometry/setYLength      485 mm
/gate/waterbox/geometry/setZLength      485 mm
/gate/waterbox/vis/setColor             blue

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList QGSP_BERT_HP

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      waterbox 0.5 mm
/gate/physics/Electron/SetCutInRegion   waterbox 0.5 mm
/gate/physics/Positron/SetCutInRegion   waterbox 0.5 mm


#=====================================================
# DETECTORS 
#=====================================================

# ----------------------------------------------------
# the following actor regularly store the current 
# number of event/track/step in a file
# ----------------------------------------------------

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/output-read5D.txt
/gate/actor/stat/saveEveryNSeconds 20

# ----------------------------------------------------
# the following actor stores 3D Dose/Edep distributions
# ----------------------------------------------------
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/attachTo    	     waterbox
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setVoxelSize          5 5 5 mm
/gate/actor/doseDistribution/saveEveryNSeconds     20
/gate/actor/doseDistribution/enableEdep            false
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/enableNumberOfHits    false
/gate/actor/doseDistribution/save                  output/ReadPhS/95.root


#=====================================================
# INITIALISATION
#====================================================

/gate/run/initialize

#=====================================================
# BEAMS
#=====================================================

/gate/source/addSource                       beam phaseSpace
/gate/source/beam/addPhaseSpaceFile          output/PhS_145.root
/gate/source/beam/attachTo                   PhS_Source
/gate/source/beam/useRandomSymmetry          true

#=====================================================  	 
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/noGlobalOutput
/gate/application/setTotalNumberOfPrimaries 10e+06
/gate/application/start
